# www를 루트 도메인으로 리다이렉트
server {
    listen 80;
    server_name www.junbyeol.me;
    return 301 http://junbyeol.me$request_uri;
}

#1. junbyeol.me 및 www.junbyeol.me 통합 처리
server {
    listen 80;
    server_name junbyeol.me;

    charset utf-8;

    location / {
        # 아직 메인 웹사이트 컨테이너가 없으므로 임시 메시지
        return 200 "여기는 junbyeol.me 메인 페이지입니다.";
        add_header Content-Type "text/plain; charset=utf-8";
    }
}

# 2. resume.junbyeol.me 처리
server {
    listen 80;
    server_name resume.junbyeol.me;

    charset utf-8;

    location / {
        # 아직 resume 컨테이너를 안 만들었으므로 임시 에러 메시지
        return 200 "이곳은 이력서 페이지가 들어올 자리입니다.";
        add_header Content-Type "text/plain; charset=utf-8";
    }
}

# 3. server.junbyeol.me (백엔드) 처리
server {
    listen 80;
    server_name server.junbyeol.me;

    charset utf-8;

    location / {
        return 200 "이곳은 백엔드 API 서버가 들어올 자리입니다.";
        add_header Content-Type "text/plain; charset=utf-8";
    }
}

# 3. 정의되지 않은 나머지 모든 서브도메인 처리 (Security)
server {
    listen 80 default_server;
    server_name _;

    charset utf-8;

    return 404 "잘못된 접근입니다.";
}
