server {
    listen 80;
    server_name plaza.junbyeol.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name plaza.junbyeol.me;
    charset utf-8;

    include /etc/nginx/conf.d/snippets/ssl-plaza.conf;

    location / {
        proxy_pass http://plaza-frontend:80;
        include /etc/nginx/conf.d/snippets/proxy-headers.conf;
    }
}
