server {
    listen 80;
    server_name server.junbyeol.me;
    charset utf-8;

    location / {
        return 200 "이곳은 백엔드 API 서버가 들어올 자리입니다.";
        add_header Content-Type "text/plain; charset=utf-8";
    }
}
